events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # --- O SEGREDO: DEFINIMOS O GRUPO DE SERVIDORES (UPSTREAM) ---
    upstream api_backend {
        # O Nginx faz o Round Robin automaticamente entre eles
        server backend-1:8080;
        server backend-2:8080;
        server backend-3:8080;
    }

    server {
        listen 80;

        # 1. Serve o seu Site (HTML/JS)
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # 2. Redireciona as chamadas da API para o Grupo de Servidores
        location /api/ {
            # Manda para o grupo 'api_backend' definido lá em cima
            proxy_pass http://api_backend/api/;
            
            # Configurações para passar o IP e Headers corretamente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Importante para o Cookie passar
            proxy_set_header Cookie $http_cookie;
        }
    }
}