FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package.json only to install dependencies
COPY package.json ./

RUN npm install --production

# Copy the proxy script
COPY dev-proxy.js ./

# Expose dev server port
EXPOSE 5500

CMD [ "node", "dev-proxy.js" ]
